export const mockCustomers = [
  { id: 'CUST001', name: 'John Doe', email: 'john.doe@example.com', totalSpent: 1500, outstandingDebt: 200, joinDate: '2023-01-15' },
  { id: 'CUST002', name: 'Jane Smith', email: 'jane.smith@example.com', totalSpent: 2500, outstandingDebt: 0, joinDate: '2023-02-20' },
  { id: 'CUST003', name: 'Mike Johnson', email: 'mike.j@example.com', totalSpent: 800, outstandingDebt: 50, joinDate: '2023-03-10' },
  { id: 'CUST004', name: 'Emily Davis', email: 'emily.d@example.com', totalSpent: 3200, outstandingDebt: 0, joinDate: '2023-04-05' },
  { id: 'CUST005', name: 'Chris Lee', email: 'chris.lee@example.com', totalSpent: 500, outstandingDebt: 100, joinDate: '2023-05-12' },
];

export const mockProducts = [
  {
    product_code: "P001-B1",
    name: "Máy xới đất Kubota",
    slug: "may-xoi-dat-kubota",
    description: "Máy xới đất chất lượng cao, phù hợp canh tác ruộng nhỏ và vừa. Động cơ mạnh mẽ, bền bỉ, tiết kiệm nhiên liệu, dễ dàng vận hành và bảo trì. Một công cụ không thể thiếu cho nhà nông chuyên nghiệp.",
    category_id: "cate-001",
    brand: "Kubota",
    unit: "chiếc",
    price: 15000000,
    credit_price: 16000000,
    stock: 25,
    min_stock_level: 5,
    images: "[\"https://placehold.co/600x600.png\",\"https://placehold.co/601x601.png\",\"https://placehold.co/602x602.png\"]",
    specs: "{\"Trọng lượng\": \"75kg\", \"Động cơ\": \"4 thì\", \"Dung tích\": \"212cc\", \"Công suất\": \"7 HP\"}",
    warranty_info: "Bảo hành 12 tháng tại cửa hàng. Hỗ trợ kỹ thuật 24/7.",
    supplier_id: "supp-001",
    is_active: true,
    is_deleted: false,
    hint: 'tiller agriculture'
  },
  {
    product_code: "P002-Y1",
    name: "Máy cày Yanmar",
    slug: "may-cay-yanmar",
    description: "Máy cày đa năng, hiệu suất cao, tiết kiệm nhiên liệu. Thiết kế hiện đại, khung gầm chắc chắn, phù hợp với mọi địa hình canh tác.",
    category_id: "cate-001",
    brand: "Yanmar",
    unit: "chiếc",
    price: 350000000,
    credit_price: 360000000,
    stock: 10,
    min_stock_level: 2,
    images: "[\"https://placehold.co/600x600.png\",\"https://placehold.co/601x601.png\",\"https://placehold.co/602x602.png\"]",
    specs: "{\"Trọng lượng\": \"2.5 tấn\", \"Động cơ\": \"Diesel\", \"Công suất\": \"50HP\", \"Hộp số\": \"8 tiến 2 lùi\"}",
    warranty_info: "Bảo hành 24 tháng chính hãng. Miễn phí vận chuyển toàn quốc.",
    supplier_id: "supp-002",
    is_active: true,
    is_deleted: false,
    hint: 'tractor agriculture'
  },
  {
    product_code: "P003-J1",
    name: "Máy gặt đập John Deere",
    slug: "may-gat-dap-john-deere",
    description: "Máy gặt đập liên hợp hiện đại, công suất lớn, giảm thiểu thất thoát sau thu hoạch. Buồng đập lớn, hệ thống sàng lọc hiệu quả.",
    category_id: "cate-002",
    brand: "John Deere",
    unit: "chiếc",
    price: 2500000000,
    credit_price: 2600000000,
    stock: 5,
    min_stock_level: 1,
    images: "[\"https://placehold.co/600x600.png\",\"https://placehold.co/601x601.png\",\"https://placehold.co/602x602.png\"]",
    specs: "{\"Trọng lượng\": \"15 tấn\", \"Động cơ\": \"Diesel\", \"Công suất\": \"300HP\", \"Bề rộng cắt\": \"4.5m\"}",
    warranty_info: "Bảo hành 36 tháng. Phụ tùng thay thế có sẵn.",
    supplier_id: "supp-003",
    is_active: true,
    is_deleted: false,
    hint: 'combine harvester'
  },
  {
    product_code: "P004-K1",
    name: "Máy phun thuốc STIHL",
    slug: "may-phun-thuoc-stihl",
    description: "Máy phun thuốc sâu đeo vai, nhỏ gọn, dễ sử dụng. Áp lực phun mạnh, đều, tiết kiệm thuốc.",
    category_id: "cate-003",
    brand: "STIHL",
    unit: "chiếc",
    price: 5500000,
    credit_price: 6000000,
    stock: 50,
    min_stock_level: 10,
    images: "[\"https://placehold.co/600x600.png\",\"https://placehold.co/601x601.png\"]",
    specs: "{\"Trọng lượng\": \"10kg\", \"Dung tích bình\": \"20L\", \"Lưu lượng phun\": \"2-4 L/phút\"}",
    warranty_info: "Bảo hành 6 tháng. Dễ dàng sửa chữa.",
    supplier_id: "supp-001",
    is_active: true,
    is_deleted: false,
    hint: 'sprayer farm'
  },
  {
    product_code: "P005-B2",
    name: "Máy cắt cỏ Honda",
    slug: "may-cat-co-honda",
    description: "Máy cắt cỏ cầm tay, động cơ êm ái, bền bỉ. Lưỡi cắt sắc bén, tay cầm chống rung, an toàn cho người sử dụng.",
    category_id: "cate-003",
    brand: "Honda",
    unit: "chiếc",
    price: 3500000,
    credit_price: 4000000,
    stock: 40,
    min_stock_level: 10,
    images: "[\"https://placehold.co/600x600.png\"]",
    specs: "{\"Trọng lượng\": \"8kg\", \"Động cơ\": \"GX35\", \"Loại\": \"Cầm tay\"}",
    warranty_info: "Bảo hành 12 tháng. Phụ tùng chính hãng.",
    supplier_id: "supp-002",
    is_active: true,
    is_deleted: false,
    hint: 'lawn mower'
  }
];

export const mockOrders = [
  { id: 'ORD001', customerName: 'John Doe', date: '2024-07-20', status: 'Delivered', total: 75.50 },
  { id: 'ORD002', customerName: 'Jane Smith', date: '2024-07-21', status: 'Pending', total: 120.00 },
  { id: 'ORD003', customerName: 'Mike Johnson', date: '2024-07-21', status: 'Delivered', total: 45.20 },
  { id: 'ORD004', customerName: 'Emily Davis', date: '2024-07-22', status: 'Shipped', total: 200.00 },
  { id: 'ORD005', customerName: 'Chris Lee', date: '2024-07-23', status: 'Pending', total: 30.00 },
  { id: 'ORD006', customerName: 'John Doe', date: '2024-07-23', status: 'Cancelled', total: 55.00 },
];

export const mockCategories = [
  { 
    id: 'cate-001', 
    name: 'Máy làm đất', 
    slug: 'may-lam-dat',
    description: 'Các loại máy xới, máy cày phục vụ công tác làm đất.',
    parent_id: null,
    image: 'https://placehold.co/100x100.png',
    order: 1,
    is_active: true
  },
  { 
    id: 'cate-002', 
    name: 'Máy thu hoạch', 
    slug: 'may-thu-hoach',
    description: 'Máy gặt đập, máy tuốt lúa và các thiết bị thu hoạch khác.',
    parent_id: null,
    image: 'https://placehold.co/100x100.png',
    order: 2,
    is_active: true
  },
  { 
    id: 'cate-003', 
    name: 'Dụng cụ & Thiết bị',
    slug: 'dung-cu-thiet-bi', 
    description: 'Các loại máy móc, dụng cụ cầm tay hỗ trợ nông nghiệp.',
    parent_id: null,
    image: 'https://placehold.co/100x100.png',
    order: 3,
    is_active: false
  },
];
